/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 scene.gltf 
Author: Veysel Gök (https://sketchfab.com/veysel.gok.vg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/avengers-endgame-df0ab2d8550b430e96819e1d3967bdcf
Title: Avengers - Endgame
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -5.03, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <mesh geometry={nodes['platform_Material_#143_0'].geometry} material={materials.Material_143} />
        <mesh geometry={nodes['platform_Material_#118_0'].geometry} material={materials.Material_118} />
        <mesh geometry={nodes['platform_Material_#117_0'].geometry} material={materials.Material_117} />
      </group>
      <group position={[-14.184, 85.704, 7.186]} rotation={[Math.PI, -0.105, 0]} scale={21.762}>
        <mesh geometry={nodes['Object002_Material_#110_0'].geometry} material={materials.Material_110} position={[0, 3.907, 0]} />
        <mesh geometry={nodes['Object005_Material_#109_0'].geometry} material={materials.Material_109} position={[0, 3.907, 0]} />
        <mesh geometry={nodes.rdmobj001_wire_204204204_0.geometry} material={materials.wire_204204204} position={[0, 3.907, 0]} />
        <mesh geometry={nodes['rdmobj002_Material_#106_0'].geometry} material={materials.Material_106} position={[0, 3.907, 0]} />
        <mesh geometry={nodes['rdmobj004_Material_#113_0'].geometry} material={materials.Material_113} position={[0, 3.907, 0]} />
        <mesh geometry={nodes['rdmobj005_Material_#105_0'].geometry} material={materials.Material_105} position={[0, 3.907, 0]} />
        <mesh geometry={nodes['rdmobj006_Material_#112_0'].geometry} material={materials.Material_112} position={[0, 3.907, 0]} />
        <mesh geometry={nodes['rdmobj008_Material_#108_0'].geometry} material={materials.Material_108} position={[0, 3.907, 0]} />
      </group>
      <group position={[-15.402, 125.186, 71.464]} rotation={[0.922, 0.596, -3.049]} scale={0.789}>
        <mesh geometry={nodes['rdmobj003_Material_#101_0'].geometry} material={materials.Material_101} position={[1.603, -0.179, -1.489]} />
        <mesh geometry={nodes['rdmobj00_Material_#102_0'].geometry} material={materials.Material_102} position={[1.603, -0.179, -1.489]} />
      </group>
      <mesh geometry={nodes['mjolnir_Material_#99_0'].geometry} material={materials.Material_99} position={[-24.863, 154.127, -27.383]} rotation={[-0.598, 0.143, 0.797]} scale={63.143} />
      <mesh geometry={nodes['text_Material_#156_0'].geometry} material={materials.Material_156} position={[0, 0.027, 112.416]} />
      <mesh geometry={nodes['light1_Material_#157_0'].geometry} material={materials.Material_157} position={[-4.508, 94.102, -129.746]} />
      <mesh geometry={nodes['light2_Material_#158_0'].geometry} material={materials.Material_158} position={[-81.353, 112.441, 0]} rotation={[0, -Math.PI / 4, 0]} scale={0.956} />
      <mesh geometry={nodes['light3_Material_#158_0'].geometry} material={materials.Material_158} position={[72.391, 121.984, 0]} rotation={[0, Math.PI / 4, 0]} scale={0.884} />
      <mesh geometry={nodes['light4_Material_#159_0'].geometry} material={materials.Material_159} position={[-17.997, 177.921, 8.938]} rotation={[-0.484, 0, 0]} scale={[0.369, 0.072, 0.277]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
