/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 scene.gltf 
Author: CAPTAAINR (https://sketchfab.com/CAPTAAINR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iron-man-old-suit-7b2022b26cfe49a8b0476f61e042994e
Title: Iron-Man old suit
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene2.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.216, -0.561]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.MI_Hightower_SLC_TomatoSuit_Alt} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.A_Face} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
